title: Juan Flores
description: Data Scientist 
plugins:
- jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


